name: GitHub Page
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install
        run: npm install
      - name: Build 
        run: npm run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: discord-test # Replace with your Cloudflare project name
          directory: dist # Replace if your build directory is different
          wranglerVersion: "3"
        env:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
